"use client";

import Link from "next/link";
import type { Organization } from "./organizations-data";
import { PlanPill } from "./pills";
import { DASH } from "./theme";

const HEAD_CLASS = "px-4 py-3 text-left text-[11px] font-semibold uppercase tracking-[0.08em] text-[#9CA3AF]";

export function TopOrganizationsCard({ organizations }: { organizations: Organization[] }) {
  const ranked = [...organizations].sort((left, right) => (right.posts + right.images) - (left.posts + left.images)).slice(0, 5);
  const max = Math.max(1, ...ranked.map((org) => org.posts + org.images));
  return <div className="rounded-2xl border bg-white" style={{ borderColor: DASH.border }}><div className="flex items-start justify-between gap-4 p-6"><div><h2 className="text-lg font-bold" style={{ color: DASH.heading }}>Top Organizations</h2><p className="mt-1 text-sm" style={{ color: DASH.muted }}>By generated content this month</p></div><Link href="/dashboard/organizations" className="shrink-0 text-sm font-bold hover:underline" style={{ color: DASH.accent }}>View all organizations →</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[1080px] border-collapse text-left"><thead><tr className="border-y" style={{ borderColor: DASH.border }}><th className={HEAD_CLASS}>Organization</th><th className={HEAD_CLASS}>Owner Email</th><th className={HEAD_CLASS}>Plan</th><th className={HEAD_CLASS}>Users</th><th className={HEAD_CLASS}>Posts</th><th className={HEAD_CLASS}>Images</th><th className={HEAD_CLASS}>Activity</th></tr></thead><tbody>{ranked.map((org) => { const score = Math.round(((org.posts + org.images) / max) * 100); return <tr key={org.slug} className="border-b last:border-b-0" style={{ borderColor: DASH.border }}><td className="px-4 py-4"><Link href={`/dashboard/organizations/${org.slug}`} className="flex items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border text-lg" style={{ borderColor: DASH.border, backgroundColor: "#FAFAFB" }}>{org.emoji}</span><span><span className="block text-[15px] font-bold" style={{ color: DASH.heading }}>{org.name}</span><span className="mt-0.5 block text-[13px]" style={{ color: DASH.muted }}>{org.sector}</span></span></Link></td><td className="whitespace-nowrap px-4 py-4 text-[14px]">{org.ownerEmail ? <a href={`mailto:${org.ownerEmail}`} className="font-medium hover:underline" style={{ color: DASH.accent }}>{org.ownerEmail}</a> : <span style={{ color: DASH.muted }}>Not provided</span>}</td><td className="px-4 py-4"><PlanPill plan={org.plan} /></td><td className="px-4 py-4 text-left text-[15px]" style={{ color: DASH.heading }}>{org.users}</td><td className="px-4 py-4 text-left text-[15px]" style={{ color: DASH.heading }}>{org.posts}</td><td className="px-4 py-4 text-left text-[15px]" style={{ color: DASH.heading }}>{org.images}</td><td className="px-4 py-4"><div className="flex items-center gap-3"><div className="h-1.5 w-28 overflow-hidden rounded-full bg-[#EFEDF2]"><div className="h-full rounded-full" style={{ width: `${score}%`, backgroundColor: DASH.plum }} /></div><span className="text-[13px]" style={{ color: DASH.muted }}>{score}</span></div></td></tr>; })}</tbody></table>{!ranked.length && <p className="p-6 text-sm" style={{ color: DASH.muted }}>No organizations available.</p>}</div></div>;
}
